version: "3.8"  # optional since v1.27.0
# docker-compose -up --build

services:
  frontend:
    build:
 
        dockerfile: Dockerfile.angular

    ports:
      - "4200:80"
    links:
      - "backend"

  backend:
      build:
        context: .
        dockerfile: Dockerfile.python

      ports:
       - "5000:5000"
       - "8085:8085"
      environment:
        - ip=0.0.0.0
      privileged: true
     